# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'turtlebot_controller.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QButtonGroup, QComboBox, QGroupBox,
    QLabel, QListWidget, QListWidgetItem, QPushButton,
    QRadioButton, QSizePolicy, QStackedWidget, QTextEdit,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(645, 526)
        self.stackedWidget = QStackedWidget(Form)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(20, 30, 601, 471))
        self.Page_main = QWidget()
        self.Page_main.setObjectName(u"Page_main")
        self.go_BP = QPushButton(self.Page_main)
        self.go_BP.setObjectName(u"go_BP")
        self.go_BP.setGeometry(QRect(80, 280, 121, 81))
        self.go_FP = QPushButton(self.Page_main)
        self.go_FP.setObjectName(u"go_FP")
        self.go_FP.setGeometry(QRect(240, 280, 121, 81))
        self.go_AP = QPushButton(self.Page_main)
        self.go_AP.setObjectName(u"go_AP")
        self.go_AP.setGeometry(QRect(400, 280, 121, 81))
        self.Title = QTextEdit(self.Page_main)
        self.Title.setObjectName(u"Title")
        self.Title.setEnabled(True)
        self.Title.setGeometry(QRect(170, 80, 261, 41))
        font = QFont()
        font.setBold(True)
        font.setItalic(False)
        self.Title.setFont(font)
        self.Title.setMouseTracking(True)
        self.Title.setAcceptDrops(True)
        self.Title.setReadOnly(True)
        self.stackedWidget.addWidget(self.Page_main)
        self.page_Button = QWidget()
        self.page_Button.setObjectName(u"page_Button")
        self.label = QLabel(self.page_Button)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 10, 131, 51))
        self.btn_Go = QPushButton(self.page_Button)
        self.btn_Go.setObjectName(u"btn_Go")
        self.btn_Go.setGeometry(QRect(250, 130, 95, 81))
        self.btn_Stop = QPushButton(self.page_Button)
        self.btn_Stop.setObjectName(u"btn_Stop")
        self.btn_Stop.setGeometry(QRect(250, 220, 95, 81))
        self.btn_Back = QPushButton(self.page_Button)
        self.btn_Back.setObjectName(u"btn_Back")
        self.btn_Back.setGeometry(QRect(250, 310, 95, 81))
        self.btn_TRight = QPushButton(self.page_Button)
        self.btn_TRight.setObjectName(u"btn_TRight")
        self.btn_TRight.setGeometry(QRect(350, 220, 95, 81))
        self.btn_TLeft = QPushButton(self.page_Button)
        self.btn_TLeft.setObjectName(u"btn_TLeft")
        self.btn_TLeft.setGeometry(QRect(150, 220, 95, 81))
        self.btn_MP = QPushButton(self.page_Button)
        self.btn_MP.setObjectName(u"btn_MP")
        self.btn_MP.setGeometry(QRect(500, 10, 81, 41))
        font1 = QFont()
        font1.setBold(True)
        self.btn_MP.setFont(font1)
        self.stackedWidget.addWidget(self.page_Button)
        self.page_Figure = QWidget()
        self.page_Figure.setObjectName(u"page_Figure")
        self.label_3 = QLabel(self.page_Figure)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 10, 131, 51))
        self.gruop_figure = QGroupBox(self.page_Figure)
        self.gruop_figure.setObjectName(u"gruop_figure")
        self.gruop_figure.setGeometry(QRect(90, 160, 101, 131))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(True)
        self.gruop_figure.setFont(font2)
        self.btn_triangle = QRadioButton(self.gruop_figure)
        self.group_btnFigure = QButtonGroup(Form)
        self.group_btnFigure.setObjectName(u"group_btnFigure")
        self.group_btnFigure.addButton(self.btn_triangle)
        self.btn_triangle.setObjectName(u"btn_triangle")
        self.btn_triangle.setGeometry(QRect(20, 40, 71, 22))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(False)
        self.btn_triangle.setFont(font3)
        self.btn_square = QRadioButton(self.gruop_figure)
        self.group_btnFigure.addButton(self.btn_square)
        self.btn_square.setObjectName(u"btn_square")
        self.btn_square.setGeometry(QRect(20, 90, 71, 22))
        self.btn_square.setFont(font3)
        self.box_distance = QComboBox(self.page_Figure)
        self.box_distance.setObjectName(u"box_distance")
        self.box_distance.setGeometry(QRect(260, 180, 91, 25))
        self.label_4 = QLabel(self.page_Figure)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(260, 160, 81, 17))
        self.label_4.setFont(font1)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.box_count = QComboBox(self.page_Figure)
        self.box_count.setObjectName(u"box_count")
        self.box_count.setGeometry(QRect(410, 180, 91, 25))
        self.label_5 = QLabel(self.page_Figure)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(410, 160, 81, 17))
        self.label_5.setFont(font1)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.btn_startFigure = QPushButton(self.page_Figure)
        self.btn_startFigure.setObjectName(u"btn_startFigure")
        self.btn_startFigure.setGeometry(QRect(170, 330, 121, 51))
        font4 = QFont()
        font4.setPointSize(17)
        font4.setBold(True)
        self.btn_startFigure.setFont(font4)
        self.btn_MP_2 = QPushButton(self.page_Figure)
        self.btn_MP_2.setObjectName(u"btn_MP_2")
        self.btn_MP_2.setGeometry(QRect(500, 10, 81, 41))
        self.btn_MP_2.setFont(font1)
        self.btn_stopFigure = QPushButton(self.page_Figure)
        self.btn_stopFigure.setObjectName(u"btn_stopFigure")
        self.btn_stopFigure.setGeometry(QRect(310, 330, 121, 51))
        self.btn_stopFigure.setFont(font4)
        self.stackedWidget.addWidget(self.page_Figure)
        self.gruop_figure.raise_()
        self.label_3.raise_()
        self.box_distance.raise_()
        self.label_4.raise_()
        self.box_count.raise_()
        self.label_5.raise_()
        self.btn_startFigure.raise_()
        self.btn_MP_2.raise_()
        self.btn_stopFigure.raise_()
        self.page_Auto = QWidget()
        self.page_Auto.setObjectName(u"page_Auto")
        self.label_6 = QLabel(self.page_Auto)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 10, 131, 51))
        self.list_Dlog = QListWidget(self.page_Auto)
        self.list_Dlog.setObjectName(u"list_Dlog")
        self.list_Dlog.setGeometry(QRect(90, 130, 421, 301))
        self.label_7 = QLabel(self.page_Auto)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(90, 106, 81, 21))
        self.label_7.setFont(font1)
        self.btn_autoStart = QPushButton(self.page_Auto)
        self.btn_autoStart.setObjectName(u"btn_autoStart")
        self.btn_autoStart.setGeometry(QRect(380, 100, 61, 25))
        self.btn_MP_3 = QPushButton(self.page_Auto)
        self.btn_MP_3.setObjectName(u"btn_MP_3")
        self.btn_MP_3.setGeometry(QRect(500, 10, 81, 41))
        self.btn_MP_3.setFont(font1)
        self.btn_autoStop = QPushButton(self.page_Auto)
        self.btn_autoStop.setObjectName(u"btn_autoStop")
        self.btn_autoStop.setGeometry(QRect(450, 100, 61, 25))
        self.stackedWidget.addWidget(self.page_Auto)

        self.retranslateUi(Form)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Turtlebot_Controller", None))
        self.go_BP.setText(QCoreApplication.translate("Form", u"Button \uc81c\uc5b4", None))
        self.go_FP.setText(QCoreApplication.translate("Form", u"\ub3c4\ud615 \uc8fc\ud589", None))
        self.go_AP.setText(QCoreApplication.translate("Form", u"\ucda9\ub3cc \ubc29\uc9c0 \uc8fc\ud589", None))
        self.Title.setHtml(QCoreApplication.translate("Form", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:700; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">TurtleBot \uc81c\uc5b4 \ud504\ub85c\uadf8\ub7a8</span></p></body></html>", None))
        self.label.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">Button \uc81c\uc5b4</span></p></body></html>", None))
        self.btn_Go.setText(QCoreApplication.translate("Form", u"Go", None))
        self.btn_Stop.setText(QCoreApplication.translate("Form", u"Stop", None))
        self.btn_Back.setText(QCoreApplication.translate("Form", u"Back", None))
        self.btn_TRight.setText(QCoreApplication.translate("Form", u"Turn Right", None))
        self.btn_TLeft.setText(QCoreApplication.translate("Form", u"Turn Left", None))
        self.btn_MP.setText(QCoreApplication.translate("Form", u"Main", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">\ub3c4\ud615 \uc8fc\ud589</span></p></body></html>", None))
        self.gruop_figure.setTitle(QCoreApplication.translate("Form", u"\ub3c4\ud615", None))
        self.btn_triangle.setText(QCoreApplication.translate("Form", u"\uc0bc\uac01\ud615", None))
        self.btn_square.setText(QCoreApplication.translate("Form", u"\uc0ac\uac01\ud615", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\uac70\ub9ac(m)", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\ud69f\uc218", None))
        self.btn_startFigure.setText(QCoreApplication.translate("Form", u"\uc774\ub3d9", None))
        self.btn_MP_2.setText(QCoreApplication.translate("Form", u"Main", None))
        self.btn_stopFigure.setText(QCoreApplication.translate("Form", u"\uc911\uc9c0", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">\ucda9\ub3cc \ubc29\uc9c0 \uc8fc\ud589</span></p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"\uc8fc\ud589 \uc0c1\ud0dc", None))
        self.btn_autoStart.setText(QCoreApplication.translate("Form", u"Start", None))
        self.btn_MP_3.setText(QCoreApplication.translate("Form", u"Main", None))
        self.btn_autoStop.setText(QCoreApplication.translate("Form", u"Stop", None))
    # retranslateUi

